# Cliente 4 / Servidor 1: Ubuntu 22.10
FROM ubuntu:22.10
ENV DEBIAN_FRONTEND=noninteractive

# Corregir repositorios EOL (archive Y security)
RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

# Instalar cliente, servidor y herramientas
RUN apt-get update && \
    apt-get install -y openssh-client openssh-server tcpdump net-tools nano && \
    rm -rf /var/lib/apt/lists/*

# 1.2: Crear usuario "prueba" con contraseña "prueba"
RUN useradd -m -s /bin/bash prueba && \
    echo "prueba:prueba" | chpasswd

# Configurar servidor SSH para permitir login con contraseña
RUN mkdir -p /var/run/sshd
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
RUN sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Exponer el puerto SSH
EXPOSE 22

# Iniciar el servidor SSH
CMD ["/usr/sbin/sshd", "-D"]
