# Cliente 2: Ubuntu 18.10
FROM ubuntu:18.10
ENV DEBIAN_FRONTEND=noninteractive

# Corregir repositorios EOL (archive Y security)
RUN sed -i 's/archive.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/old-releases.ubuntu.com/g' /etc/apt/sources.list

# Instalar cliente OpenSSH y herramientas de red
RUN apt-get update && \
    apt-get install -y openssh-client tcpdump net-tools && \
    rm -rf /var/lib/apt/lists/*

CMD ["tail", "-f", "/dev/null"]
